require('core/options')
require('core/lazy')
require('core/plugins')
require('core/mappings')
require('core/autocmd')

require('setup/nvim-treesitter')
require('setup/indent-blankline')
require('setup/nvim-cmp')
require('setup/nvim-lspconfig')
require('setup/telescope')
require('setup/nvim-lint')
require('setup/autopairs')
require('setup/yanky')
